# Generated by Django 3.2.8 on 2021-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
