# Generated by Django 3.2.8 on 2021-11-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_price',
        ),
    ]
