# Generated by Django 3.2.8 on 2021-11-11 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_items_watchlist_auction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'bid'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'watchlist'},
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('auction', 'user')},
        ),
    ]
